version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    volumes:
      - db-data:/var/lib/mysql
  ctf-app:
    build:
      context: .
      dockerfile: kataloog/Dockerfile
    ports:
      - "4173:4173"
    environment:
      DATABASE_URL: "mysql://root:mysecretpassword@dbhost:3306/local"
    depends_on:
      - db
volumes:
  db-data:
