version: '3.9'
services:
  db:
    image: mysql
    container_name: ctf-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      retries: 5

  ctf-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    environment:
      DATABASE_URL: 'mysql://root:mysecretpassword@dbhost:3306/local'
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
